[package]
name = "s3_fuse"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.79.0"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
