version: '3.8'

services:
  minio:
    container_name: "${MINIO_DOCKER_NAME:-minio-main}"
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"        # MinIO API
      - "127.0.0.1:9001:9001"        # MinIO Console
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - s3-data:/data
    
volumes:
  s3-data: